name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use your desired Python ver

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx_rtd_theme  # Adjust to your Sphinx dependencies

    - name: Build the documentation
      run: |
        cd docs
        sphinx-build -b html source build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
